### ISSUE TITLE
Add Testing for Collection class

### ISSUE THREAD

**Issue by cagandhi** [jaymodi98/Sync-Ends#19]
Write unit tests for Collection class

**Comment by cagandhi** [comment]
Could someone take a look at this and check if the test structure is proper?

**Comment by jaymodi98** [comment]
Could you add the collection initializing and endpoint code in a setUp() method as described in this link: https://docs.python.org/3/library/unittest.html#organizing-test-code. Currently, collection is needed to be created in both the test methods so it seems redundant.

**Comment by cagandhi** [comment]
Added the setUp() method and cleaned the code. Pushed the commit in the pull request #20
