### ISSUE TITLE
Update zenodo badge and readme to remove old project's details

### ISSUE THREAD

**Issue by jaymodi98** [jaymodi98/Sync-Ends#27]

**Comment by sj23patel** [comment]
According to [this](https://docs.google.com/document/u/1/d/e/2PACX-1vRHzSw2iOdojUdsdFYjalLqFZu9MUDegM1oFOr3yHCprLkIH39NqcoV3CSb91X_xdWvmsWf14kQ6pbF/pub), we do not require Author names in README.

**Comment by cagandhi** [comment]
Yeah, I think this makes sense. Go ahead and make the change.
