### ISSUE TITLE
Add 'What' documentation in code

### ISSUE THREAD

**Issue by cagandhi** [jaymodi98/Sync-Ends#34]

**Comment by sj23patel** [comment]
Found this tool called [pdoc3](https://pdoc3.github.io/pdoc/) to simply generate html file for point descriptions of function/class from docstrings in code. Maybe we can use this.

**Comment by cagandhi** [comment]
Ok, I will take a look at this. If it generates clear descriptions from docstrings, we can surely use this.

**Comment by cagandhi** [comment]
Used pdoc3 as discussed to generate descriptions for the class and methods. Pushed the commits in this #38. Could someone review this? Let me know if we need to add something.

**Comment by jaymodi98** [comment]
So just the docstring added to source files? Are they being converted to markdown/HTML? Are the HTML files a part of the documentation or are they just "ignore" files?

**Comment by cagandhi** [comment]
So, `pdoc3` internally converts all docstrings in code files as HTML files. The HTML files added are `pdoc's` conversion of comments to beautiful HTML web pages. The file `docs/src/index.html` is the main file for documentation and the other HTML files are attached as hyperlinks in this index file.

**Comment by jaymodi98** [comment]
Got it! The index.html looks good. I think the issue should be closed now
