### ISSUE TITLE
CLI does not terminate its run

### ISSUE THREAD

**Issue by cagandhi** [jaymodi98/Sync-Ends#39]

**Comment by cagandhi** [comment]
@oaaky Any idea what might be happening? I think it's because we have this `while True` statement in start() [here](https://github.com/jaymodi98/Sync-Ends/blob/a53cc9e72a290c6eea8252554e8e0e27ba558112/src/sync_ends_service.py#L243).

**Comment by jaymodi98** [comment]
@oaaky   can you please tell me how to reproduce this bug?

**Comment by oaaky** [comment]
Yeah I did the RCA of this issue. It looks like there is problem with reading the schema file. Try to debug the code where we are reading the old schema of the collection from the file.
