### ISSUE TITLE
Add test cases to improve the code coverage and better testing of code

### ISSUE THREAD

**Issue by jaymodi98** [jaymodi98/Sync-Ends#4]

**Comment by jaymodi98** [comment]
This seems a highly generalized issue. Need to divide this properly in small issues.

**Comment by cagandhi** [comment]
Referencing issue #28 and issue #19 which deal with tests for EndPoint and Collection class

**Comment by jaymodi98** [comment]
I have created 2 new issues: #45 and #44 .
This issue should be closed now

**Comment by cagandhi** [comment]
All the test related issues have been referenced here. Closing this issue now.
