### ISSUE TITLE
Use a data storage mechanism (secure database) to store API collection details.

### ISSUE THREAD

**Issue by cagandhi** [jaymodi98/Sync-Ends#9]

**Comment by sj23patel** [comment]
Given that we are utilizing file-diffs, using of a database might introduce unnecessary overheads.

**Comment by jaymodi98** [comment]
I agree with @sj23patel , the existing light-weight solution should be fine

**Comment by nirav1997** [comment]
But using database will make it more robust and flexible for deployment and distribution.

**Comment by cagandhi** [comment]
But, I think a text file should suffice our purpose since the data is stored as a json and all we need to do is diff jsons. I agree with @sj23patel and @jaymodi98 that database is a heavy solution for this problem.

**Comment by oaaky** [comment]
Using the database to store the file diff will add unnecessary overhead of maintenance
Let continue with the current implementation and store the file diff on local system.

**Comment by oaaky** [comment]
Closing the issue.
